/*
 * KadrigamGUIView.java
 */

package kadrigamgui;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * The application's main frame.
 */
public class KadrigamGUIView extends FrameView {

    public KadrigamGUIView(SingleFrameApplication app) {
        super(app);

        initComponents();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = KadrigamGUIApp.getApplication().getMainFrame();
            aboutBox = new KadrigamGUIAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        KadrigamGUIApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        enemies = new javax.swing.JPanel();
        enemy1 = new javax.swing.JButton();
        enemy2 = new javax.swing.JButton();
        enemy3 = new javax.swing.JButton();
        enemy4 = new javax.swing.JButton();
        enemy5 = new javax.swing.JButton();
        allies = new javax.swing.JPanel();
        ally1 = new javax.swing.JButton();
        ally2 = new javax.swing.JButton();
        ally3 = new javax.swing.JButton();
        ally4 = new javax.swing.JButton();
        ally5 = new javax.swing.JButton();
        hand = new javax.swing.JPanel();

        mainPanel.setName("mainPanel"); // NOI18N

        enemies.setName("enemies"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(kadrigamgui.KadrigamGUIApp.class).getContext().getResourceMap(KadrigamGUIView.class);
        enemy1.setText(resourceMap.getString("enemy1.text")); // NOI18N
        enemy1.setName("enemy1"); // NOI18N

        enemy2.setText(resourceMap.getString("enemy2.text")); // NOI18N
        enemy2.setName("enemy2"); // NOI18N

        enemy3.setText(resourceMap.getString("enemy3.text")); // NOI18N
        enemy3.setName("enemy3"); // NOI18N

        enemy4.setText(resourceMap.getString("enemy4.text")); // NOI18N
        enemy4.setName("enemy4"); // NOI18N

        enemy5.setText(resourceMap.getString("enemy5.text")); // NOI18N
        enemy5.setName("enemy5"); // NOI18N

        org.jdesktop.layout.GroupLayout enemiesLayout = new org.jdesktop.layout.GroupLayout(enemies);
        enemies.setLayout(enemiesLayout);
        enemiesLayout.setHorizontalGroup(
            enemiesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(enemiesLayout.createSequentialGroup()
                .add(enemy1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 204, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(enemy2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(enemy3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(enemy4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(enemy5)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        enemiesLayout.linkSize(new java.awt.Component[] {enemy1, enemy2, enemy3, enemy4, enemy5}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        enemiesLayout.setVerticalGroup(
            enemiesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(enemiesLayout.createSequentialGroup()
                .add(enemiesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(enemy1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 286, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(enemy2)
                    .add(enemy3)
                    .add(enemy4)
                    .add(enemy5))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        enemiesLayout.linkSize(new java.awt.Component[] {enemy1, enemy2, enemy3, enemy4, enemy5}, org.jdesktop.layout.GroupLayout.VERTICAL);

        allies.setName("allies"); // NOI18N

        ally1.setText(resourceMap.getString("ally1.text")); // NOI18N
        ally1.setName("ally1"); // NOI18N
        ally1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ally1StateChanged(evt);
            }
        });

        ally2.setText(resourceMap.getString("ally2.text")); // NOI18N
        ally2.setName("ally2"); // NOI18N

        ally3.setText(resourceMap.getString("ally3.text")); // NOI18N
        ally3.setName("ally3"); // NOI18N

        ally4.setText(resourceMap.getString("ally4.text")); // NOI18N
        ally4.setName("ally4"); // NOI18N

        ally5.setText(resourceMap.getString("ally5.text")); // NOI18N
        ally5.setName("ally5"); // NOI18N

        org.jdesktop.layout.GroupLayout alliesLayout = new org.jdesktop.layout.GroupLayout(allies);
        allies.setLayout(alliesLayout);
        alliesLayout.setHorizontalGroup(
            alliesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(alliesLayout.createSequentialGroup()
                .add(5, 5, 5)
                .add(ally1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 204, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ally2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 135, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ally3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(ally4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ally5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(331, Short.MAX_VALUE))
        );

        alliesLayout.linkSize(new java.awt.Component[] {ally1, ally2, ally3, ally4, ally5}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        alliesLayout.setVerticalGroup(
            alliesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(alliesLayout.createSequentialGroup()
                .add(alliesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE, false)
                    .add(ally1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 314, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ally2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ally5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ally3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ally4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        alliesLayout.linkSize(new java.awt.Component[] {ally1, ally2, ally3, ally4, ally5}, org.jdesktop.layout.GroupLayout.VERTICAL);

        hand.setName("hand"); // NOI18N

        org.jdesktop.layout.GroupLayout handLayout = new org.jdesktop.layout.GroupLayout(hand);
        hand.setLayout(handLayout);
        handLayout.setHorizontalGroup(
            handLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1494, Short.MAX_VALUE)
        );
        handLayout.setVerticalGroup(
            handLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 296, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout mainPanelLayout = new org.jdesktop.layout.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(359, Short.MAX_VALUE)
                .add(allies, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .add(mainPanelLayout.createSequentialGroup()
                .add(168, 168, 168)
                .add(hand, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(367, Short.MAX_VALUE)
                .add(enemies, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(242, 242, 242))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(471, Short.MAX_VALUE)
                .add(enemies, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(allies, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(12, 12, 12)
                .add(hand, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(62, 62, 62))
        );

        setComponent(mainPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void ally1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ally1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ally1StateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel allies;
    private javax.swing.JButton ally1;
    private javax.swing.JButton ally2;
    private javax.swing.JButton ally3;
    private javax.swing.JButton ally4;
    private javax.swing.JButton ally5;
    private javax.swing.JPanel enemies;
    private javax.swing.JButton enemy1;
    private javax.swing.JButton enemy2;
    private javax.swing.JButton enemy3;
    private javax.swing.JButton enemy4;
    private javax.swing.JButton enemy5;
    private javax.swing.JPanel hand;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
}
