
import javax.swing.DefaultListModel;
import java.util.Set;

public class DeckListUI extends javax.swing.JFrame {

    /** Creates new form DeckListUI */
    private User user;

    public DeckListUI(User u) {
        user = u;
        initComponents();
        populate();
        username.setText(user.getAccountName());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deckList = new javax.swing.JList();
        editDeckButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Select your deck!");

        username.setText("User");

        deckList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                deckListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(deckList);

        editDeckButton.setText("Edit Deck");
        editDeckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDeckButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(editDeckButton)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(username))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editDeckButton))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deckListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_deckListValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_deckListValueChanged

    private void editDeckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDeckButtonActionPerformed
        String s = (String)deckList.getSelectedValue();
        EditDeckUI ed = new EditDeckUI(user, s);
        ed.run();
        dispose();
    }//GEN-LAST:event_editDeckButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void run() {
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
        new DeckListUI().setVisible(true);
        }
        });
         */
        setVisible(true);
    }

    // populates list
    public void populate() {
        DefaultListModel model = new DefaultListModel();
        deckList.setModel(model);

        Set s = user.getDeckList().deckSet();
        for (Object o : s) {
            model.addElement((String)o);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList deckList;
    private javax.swing.JButton editDeckButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
