/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditorUI.java
 *
 * Created on May 2, 2010, 3:22:34 PM
 */
/**
 *
 * @author Willie
 */
public class EditorUI extends javax.swing.JFrame {

    /** Creates new form EditorUI */
    public EditorUI() {
        initComponents();
        createDeckButton.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        createCardButton = new javax.swing.JButton();
        eidtDeckButton = new javax.swing.JButton();
        createDeckText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        createDeckButton = new javax.swing.JButton();
        successfulDeckLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, new javax.swing.JLabel(), org.jdesktop.beansbinding.ELProperty.create("${text}"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        createCardButton.setText("Create Card");
        createCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCardButtonActionPerformed(evt);
            }
        });

        eidtDeckButton.setText("Edit Decks");
        eidtDeckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eidtDeckButtonActionPerformed(evt);
            }
        });

        createDeckText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                createDeckTextKeyTyped(evt);
            }
        });

        jLabel1.setText("Deck Name:");

        createDeckButton.setText("Create");
        createDeckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDeckButtonActionPerformed(evt);
            }
        });

        successfulDeckLabel.setBackground(new java.awt.Color(204, 204, 204));
        successfulDeckLabel.setText("checks if deck is created");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(createDeckText, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(successfulDeckLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createCardButton)
                    .addComponent(eidtDeckButton)
                    .addComponent(createDeckButton))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(createCardButton)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(createDeckText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createDeckButton))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eidtDeckButton)
                    .addComponent(successfulDeckLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createCardButtonActionPerformed

    private void eidtDeckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eidtDeckButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eidtDeckButtonActionPerformed

    private void createDeckTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_createDeckTextKeyTyped
        if (createDeckText.getText().length() > 0) {
            createDeckButton.setEnabled(true);
        } else {
            createDeckButton.setEnabled(false);
        }
    }//GEN-LAST:event_createDeckTextKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowOpened

    private void createDeckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDeckButtonActionPerformed
        String newDeckName = createDeckText.getText();
        System.out.println(newDeckName);
        System.out.prtinln(user.getAccountName());
            //Login.serialize(user, user.getAccountName());
        
    }//GEN-LAST:event_createDeckButtonActionPerformed

    public String getUserName() { return user.getAccountName(); }
    /**
     * @param args the command line arguments
     */
    public void run(User u) {
        user=u;
        System.out.println(user.getAccountName());
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {


                new EditorUI().setVisible(true);
                
            }
        });
    }

    private User user;
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createCardButton;
    private javax.swing.JButton createDeckButton;
    private javax.swing.JTextField createDeckText;
    private javax.swing.JButton eidtDeckButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel successfulDeckLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
