/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GameStartUI.java
 *
 * Created on May 4, 2010, 1:01:47 AM
 */
/**
 *
 * @author aidandaly
 */
import javax.swing.DefaultListModel;
import java.util.Set;

public class GameStartUI extends javax.swing.JFrame {

    /** Creates new form GameStartUI */
    public GameStartUI(User u1, User u2) {
        initComponents();
        user1 = u1;
        user2 = u2;
        populateUser1();
        populateUser2();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        user2Deck = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        user1Deck = new javax.swing.JList();
        start = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(user2Deck);

        jScrollPane2.setViewportView(user1Deck);

        start.setText("Start Game!");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("Please Select Decks to Use");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(27, 27, 27)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(start)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(131, 131, 131)
                .add(jLabel3)
                .addContainerGap(129, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(65, 65, 65)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 215, Short.MAX_VALUE)
                .add(jLabel1)
                .add(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 46, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(79, 79, 79)
                        .add(start, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        String s1 = (String) user1Deck.getSelectedValue();
        String s2 = (String) user2Deck.getSelectedValue();
        CardCollection c1 = user1.getDeck(s1);
        CardCollection c2 = user2.getDeck(s2);
        CardPile deck1 = c1.shuffleToPile();
        CardPile deck2 = c2.shuffleToPile();
        Player p1 = new HumanPlayer(deck1,user1.getAccountName());
        Player p2 = new HumanPlayer(deck2,user2.getAccountName());
        Game g = new StandardGame(p1, p2);
        System.out.println("Game set up");
        dispose();
        //g.play();
    }//GEN-LAST:event_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public void populateUser1() {
        DefaultListModel model = new DefaultListModel();
        user1Deck.setModel(model);

        Set s = user1.getDeckList().deckSet();
        for (Object o : s) {
            model.addElement((String) o);
        }
    }

    public void populateUser2() {
        DefaultListModel model = new DefaultListModel();
        user2Deck.setModel(model);

        Set s = user2.getDeckList().deckSet();
        for (Object o : s) {
            model.addElement((String) o);
        }
    }

    /*public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
    new GameStartUI().setVisible(true);
    }
    });
    }*/
    public void run() {
        setVisible(true);
    }
    private User user1;
    private User user2;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton start;
    private javax.swing.JList user1Deck;
    private javax.swing.JList user2Deck;
    // End of variables declaration//GEN-END:variables
}
