
import java.io.*;

public class LoginUI extends javax.swing.JFrame {

    /** Creates new form LoginUI */
    public LoginUI() {
        initComponents();
        startButton.setEnabled(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerOneText = new javax.swing.JTextField();
        playerTwoText = new javax.swing.JTextField();
        LoginLabel = new javax.swing.JLabel();
        playerOneLabel = new javax.swing.JLabel();
        playerTwoLabel = new javax.swing.JLabel();
        playerOneEditButton = new javax.swing.JButton();
        playerTwoEditButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        playerOneText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerOneTextActionPerformed(evt);
            }
        });
        playerOneText.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                playerOneTextPropertyChange(evt);
            }
        });
        playerOneText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                playerOneTextKeyTyped(evt);
            }
        });

        playerTwoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerTwoTextActionPerformed(evt);
            }
        });
        playerTwoText.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                playerTwoTextPropertyChange(evt);
            }
        });
        playerTwoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                playerTwoTextKeyTyped(evt);
            }
        });

        LoginLabel.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        LoginLabel.setForeground(new java.awt.Color(204, 0, 0));
        LoginLabel.setText("Login");

        playerOneLabel.setText("Player 1");

        playerTwoLabel.setText("Player 2");

        playerOneEditButton.setText("Edit P1");
        playerOneEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerOneEditButtonActionPerformed(evt);
            }
        });

        playerTwoEditButton.setText("Edit P2");
        playerTwoEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerTwoEditButtonActionPerformed(evt);
            }
        });

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        startButton.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                startButtonPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(LoginLabel)
                .addContainerGap(177, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(playerOneLabel)
                    .addComponent(playerTwoLabel))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerTwoText, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(playerOneText, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerOneEditButton)
                    .addComponent(playerTwoEditButton))
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addComponent(startButton)
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LoginLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(playerOneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(playerOneEditButton))
                    .addComponent(playerOneLabel))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(playerTwoLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(playerTwoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(playerTwoEditButton)))
                .addGap(44, 44, 44)
                .addComponent(startButton)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playerOneTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerOneTextActionPerformed
    }//GEN-LAST:event_playerOneTextActionPerformed

    private void playerTwoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerTwoTextActionPerformed
    }//GEN-LAST:event_playerTwoTextActionPerformed

    private void playerOneEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerOneEditButtonActionPerformed
        String player1 = playerOneText.getText();

        String filename = player1 + ".ser";

        User user1 = null;
        FileInputStream fis = null;
        ObjectInputStream in = null;

        try {
            fis = new FileInputStream(filename);
            in = new ObjectInputStream(fis);
            user1 = (User) in.readObject();
            in.close();
        } catch (IOException readEx) {
            user1 = new User(player1);
            Login.serialize(user1, player1);

            //readEx.printStackTrace();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }

        EditorUI e = new EditorUI();
        e.run(user1);

    }//GEN-LAST:event_playerOneEditButtonActionPerformed

    private void playerTwoEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerTwoEditButtonActionPerformed
        String player2 = playerTwoText.getText();

        String filename = player2 + ".ser";

        User user2 = null;
        FileInputStream fis = null;
        ObjectInputStream in = null;

        try {
            fis = new FileInputStream(filename);
            in = new ObjectInputStream(fis);
            user2 = (User) in.readObject();
            in.close();
        } catch (IOException readEx) {
            user2 = new User(player2);
            Login.serialize(user2, player2);

            //readEx.printStackTrace();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }

        EditorUI e = new EditorUI();
        e.run(user2);
    }//GEN-LAST:event_playerTwoEditButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
    }//GEN-LAST:event_startButtonActionPerformed

    private void playerOneTextPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_playerOneTextPropertyChange
    }//GEN-LAST:event_playerOneTextPropertyChange

    private void startButtonPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_startButtonPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_startButtonPropertyChange

    private void playerTwoTextPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_playerTwoTextPropertyChange
    }//GEN-LAST:event_playerTwoTextPropertyChange

    private void playerOneTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_playerOneTextKeyTyped
        if (playerOneText.getText().length() > 0
                && playerTwoText.getText().length() > 0) {
            startButton.setEnabled(true);
        } else {
            startButton.setEnabled(false);
        }
    }//GEN-LAST:event_playerOneTextKeyTyped

    private void playerTwoTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_playerTwoTextKeyTyped
        if (playerOneText.getText().length() > 0
                && playerTwoText.getText().length() > 0) {
            startButton.setEnabled(true);
        } else {
            startButton.setEnabled(false);
        }
    }//GEN-LAST:event_playerTwoTextKeyTyped


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LoginUI().setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JButton playerOneEditButton;
    private javax.swing.JLabel playerOneLabel;
    private javax.swing.JTextField playerOneText;
    private javax.swing.JButton playerTwoEditButton;
    private javax.swing.JLabel playerTwoLabel;
    private javax.swing.JTextField playerTwoText;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
